drupal_core_path: /var/www/drupal-7.x-dev
modules_dir: "{{ drupal_core_path }}/sites/all/modules"
themes_dir: "{{ drupal_core_path  }}/sites/all/themes"
libraries_dir: "{{ drupal_core_path }}/sites/all/libraries"
---


- name: get modules
  command: "drush dl -y {{ item }}"
  args:
    chdir: "{{ drupal_core_path }}"
  with_items: "{{ modules }}"

- include: features.yml

- name: enable modules
  command: "drush en -y {{ item }}"
  args:
    chdir: "{{ drupal_core_path }}"
  with_items: "{{ modules }}"

- name: Set permissions so that we can 'generate' features on the host.
  file:
    path: "{{ drupal_core_path }}/sites/all/modules/local-features"
    owner: www-data
    recurse: yes
