---

- name: get modules
  command: "drush dl -y {{ item }}"
  args:
    chdir: "{{ drupal_core_path }}"
  with_items: "{{ modules }}"

- include: cas.yml

- name: enable modules
  command: "drush en -y {{ item }}"
  args:
    chdir: "{{ drupal_core_path }}"
  with_items: "{{ modules }}"