---

- name: get modules
  command: "drush dl -y {{ item }}"
  args:
    chdir: "{{ drupal_core_path }}"
  with_items: "{{ modules }}"

#- include: tinymce.yml
- include: features.yml

- name: enable modules
  command: "drush en -y {{ item }}"
  args:
    chdir: "{{ drupal_core_path }}"
  with_items: "{{ modules }}"

- name: Set permissions so that we can 'generate' features on the host.
  file:
    path: "{{ drupal_core_path }}/sites/all/modules/features-{{ drupal_site_short_name }}"
    owner: www-data
    recurse: yes
