---
- hosts: dsl_www
  vars:
    apache_create_vhosts: true
    apache_vhosts_filename: "vhosts.conf"
    apache_remove_default_vhost: true
    apache_global_vhost_settings: |
      DirectoryIndex index.php
      DocumentRoot "/var/www/html"
      Options FollowSymLinks Indexes
      AllowOverride All
      RewriteEngine on
      RewriteRule   "^/$"  "http://lib.lsu.edu/dsl"  [R]


  roles:
    - common
    - geerlingguy.git
    - geerlingguy.apache
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush
  become: true
